### ISSUE TITLE
Running brew tap wix/brew results in error

### ISSUE THREAD

**Issue by SirajKakeh** [wix/homebrew-brew#14] opened 2022-02-28 14:09 UTC
Hey!
trying to run `brew tap wix/brew` results in this error on my machine

```
Error: Invalid formula: /opt/homebrew/Library/Taps/wix/homebrew-brew/Formula/supraworker.rb
supraworker: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the wix/brew tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/wix/homebrew-brew/Formula/supraworker.rb:9

Error: Cannot tap wix/brew: invalid syntax in tap!
```
I have a 2020 M1 macbook
can you please provide help with this?

**Comment by clangenb** [comment] 2022-02-28 14:29
The same occurs in our CI since about an hour ago

**Comment by clangenb** [comment] 2022-02-28 14:35
There is already a PR fixing the issue: #13

**Comment by clangenb** [comment] 2022-02-28 14:36
This is actually the same issue as #12, but the deprecated syntax has now been removed completely.

**Comment by clangenb** [comment] 2022-02-28 15:54
For now we patched the error in our fork. Until it is fixed here, you can use the following line instead of plain `brew tap wix/brew`

```
brew tap wix/brew https://github.com/encointer/homebrew-brew
```

**Comment by SirajKakeh** [comment] 2022-02-28 16:07
> 

that worked! much appreciated!

**Comment by SirajKakeh** [comment] 2022-02-28 16:08
> For now we patched the error in our fork. Until it is fixed here, you can use the following line instead of plain `brew tap wix/brew`
> 
> ```
> brew tap wix/brew https://github.com/encointer/homebrew-brew
> ```

this worked! much appreciated! @clangenb

**Comment by d4vidi** [comment] 2022-02-28 20:30
Duplicate of #12

**Closed as completed by d4vidi** 2022-02-28 20:30 UTC

**Comment by clangenb** [comment] 2022-03-01 07:48
As this has been fixed here, I will delete our fork now.
